### ISSUE TITLE
看看能否加入显示每个字的IRG Source?多谢

### ISSUE THREAD

**Issue by CNMan** [program-in-chinese/wubi_code_editor#11]
数据库直接用Unihan的
https://github.com/CNMan/Unicode/blob/master/Unihan/Unihan_IRGSources.txt

第二列的值对应如下：
```
kIRG_GSource	G
kIRG_HSource	H
kIRG_JSource	J
kIRG_KPSource	KP
kIRG_KSource	K
kIRG_MSource	M
kIRG_TSource	T
kIRG_USource	U
kIRG_VSource	V
```

界面上相应的显示个√、×即可
![2018-11-12_130934](https://user-images.githubusercontent.com/8692234/48328087-58357900-e67d-11e8-868d-9c32c20dbc61.png)

**Comment by nobodxbodon** [comment]
有个kRSUnicode对应哪个字母? `U+3400	kRSUnicode	1.4`

**Comment by CNMan** [comment]
那三个不用处理了

**Comment by nobodxbodon** [comment]
好. 刚才https://github.com/program-in-chinese/wubi_code_editor/pull/12 已经@你了, 请本地测试一下?
