### ISSUE TITLE
构造函数有办法弄成中文吗？

### ISSUE THREAD

**Issue by CrazyBoyFeng** [program-in-chinese/wubi_code_editor#20]
https://github.com/program-in-chinese/wubi_code_editor/blob/5646433c54dee20bad46c47b81909005b6720b1f/wubicodeeditor.py#L12

self 和 none 其实都可以汉化。不知道构造函数能不能通过什么方式汉化。  
类似 `class.__构造__=class.__init__` 这样的效果？

**Comment by nobodxbodon** [comment]
个人没研究过。请教一下 [草蟒项目](https://gitee.com/laowu2019_admin/grasspy380) 作者 @laowu2019 吧。

**Comment by laowu2019** [comment]
@CrazyBoyFeng 我把它汉化为 __初始化__，具体是在 tokenize 阶段实现的，把读入的 __初始化__ 替换为 __init__

**Comment by CrazyBoyFeng** [comment]
> 我把它汉化为 __初始化__，具体是在 tokenize 阶段实现的，把读入的 __初始化__ 替换为 __init__

这个方案需要自己实现一个解析器？有没有更轻的方法，比如猴补丁一类的。

另外，gitee 项目主页被屏蔽了。

**Comment by laowu2019** [comment]
> > 我把它汉化为 **初始化**，具体是在 tokenize 阶段实现的，把读入的 **初始化** 替换为 **init**
> 
> 这个方案需要自己实现一个解析器？有没有更轻的方法，比如猴补丁一类的。
> 
> 另外，gitee 项目主页被屏蔽了。

请你先试一试吧。我现在忙着写草蟒宝典。对目前这个版本，不想再做大的改动了。
谢谢你提醒，我也是才注意到主页隐身了，下次更新时改改敏感词。
